//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserRoleApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserRoleApp.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserRole System.
        /// </summary>
        public static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string _2 {
            get {
                return ResourceManager.GetString("2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string _3 {
            get {
                return ResourceManager.GetString("3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty.
        /// </summary>
        public static string _4 {
            get {
                return ResourceManager.GetString("4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Dashboard.
        /// </summary>
        public static string _5 {
            get {
                return ResourceManager.GetString("5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string _6 {
            get {
                return ResourceManager.GetString("6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserRole System. All rights reserved..
        /// </summary>
        public static string _9 {
            get {
                return ResourceManager.GetString("9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string access_denied_back {
            get {
                return ResourceManager.GetString("access_denied_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to view this page..
        /// </summary>
        public static string access_denied_msg {
            get {
                return ResourceManager.GetString("access_denied_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        public static string access_denied_title {
            get {
                return ResourceManager.GetString("access_denied_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string admin_cancel {
            get {
                return ResourceManager.GetString("admin_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this user?.
        /// </summary>
        public static string admin_confirm_delete {
            get {
                return ResourceManager.GetString("admin_confirm_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Dashboard.
        /// </summary>
        public static string admin_dashboard {
            get {
                return ResourceManager.GetString("admin_dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete User.
        /// </summary>
        public static string admin_delete_user {
            get {
                return ResourceManager.GetString("admin_delete_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        public static string admin_edit_user {
            get {
                return ResourceManager.GetString("admin_edit_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Users.
        /// </summary>
        public static string admin_manage_users {
            get {
                return ResourceManager.GetString("admin_manage_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string admin_save {
            get {
                return ResourceManager.GetString("admin_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string changepwd_confirm {
            get {
                return ResourceManager.GetString("changepwd_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string changepwd_email {
            get {
                return ResourceManager.GetString("changepwd_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string changepwd_new {
            get {
                return ResourceManager.GetString("changepwd_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Password.
        /// </summary>
        public static string changepwd_submit {
            get {
                return ResourceManager.GetString("changepwd_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string changepwd_title {
            get {
                return ResourceManager.GetString("changepwd_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        public static string changepwd_user_notfound {
            get {
                return ResourceManager.GetString("changepwd_user_notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request – The request could not be understood..
        /// </summary>
        public static string error_400 {
            get {
                return ResourceManager.GetString("error_400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized – Please log in to continue..
        /// </summary>
        public static string error_401 {
            get {
                return ResourceManager.GetString("error_401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden – You do not have access to this resource..
        /// </summary>
        public static string error_403 {
            get {
                return ResourceManager.GetString("error_403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Not Found – The page you requested does not exist..
        /// </summary>
        public static string error_404 {
            get {
                return ResourceManager.GetString("error_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error – Something went wrong on our end..
        /// </summary>
        public static string error_500 {
            get {
                return ResourceManager.GetString("error_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Home.
        /// </summary>
        public static string error_back_home {
            get {
                return ResourceManager.GetString("error_back_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        public static string error_title {
            get {
                return ResourceManager.GetString("error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty Dashboard.
        /// </summary>
        public static string faculty_dashboard {
            get {
                return ResourceManager.GetString("faculty_dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Students.
        /// </summary>
        public static string faculty_students {
            get {
                return ResourceManager.GetString("faculty_students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A secure role-based access system powered by JWT and ASP.NET Core Identity..
        /// </summary>
        public static string jwt_web {
            get {
                return ResourceManager.GetString("jwt_web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string lang_label {
            get {
                return ResourceManager.GetString("lang_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string login_email {
            get {
                return ResourceManager.GetString("login_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string login_forgot {
            get {
                return ResourceManager.GetString("login_forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password..
        /// </summary>
        public static string login_invalid {
            get {
                return ResourceManager.GetString("login_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string login_no_account {
            get {
                return ResourceManager.GetString("login_no_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string login_password {
            get {
                return ResourceManager.GetString("login_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register here.
        /// </summary>
        public static string login_register_link {
            get {
                return ResourceManager.GetString("login_register_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string login_remember {
            get {
                return ResourceManager.GetString("login_remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string login_submit {
            get {
                return ResourceManager.GetString("login_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to your account.
        /// </summary>
        public static string login_subtitle {
            get {
                return ResourceManager.GetString("login_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Back.
        /// </summary>
        public static string login_title {
            get {
                return ResourceManager.GetString("login_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin accounts cannot be self-registered..
        /// </summary>
        public static string register_admin_denied {
            get {
                return ResourceManager.GetString("register_admin_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string register_confirm_pwd {
            get {
                return ResourceManager.GetString("register_confirm_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string register_department {
            get {
                return ResourceManager.GetString("register_department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (optional).
        /// </summary>
        public static string register_dept_optional {
            get {
                return ResourceManager.GetString("register_dept_optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string register_email {
            get {
                return ResourceManager.GetString("register_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already registered..
        /// </summary>
        public static string register_email_taken {
            get {
                return ResourceManager.GetString("register_email_taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string register_fullname {
            get {
                return ResourceManager.GetString("register_fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string register_have_account {
            get {
                return ResourceManager.GetString("register_have_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string register_password {
            get {
                return ResourceManager.GetString("register_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. 6 characters.
        /// </summary>
        public static string register_pwd_hint {
            get {
                return ResourceManager.GetString("register_pwd_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string register_role {
            get {
                return ResourceManager.GetString("register_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Role --.
        /// </summary>
        public static string register_role_select {
            get {
                return ResourceManager.GetString("register_role_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string register_signin_link {
            get {
                return ResourceManager.GetString("register_signin_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string register_submit {
            get {
                return ResourceManager.GetString("register_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join as Faculty or Student.
        /// </summary>
        public static string register_subtitle {
            get {
                return ResourceManager.GetString("register_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string register_title {
            get {
                return ResourceManager.GetString("register_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Dashboard.
        /// </summary>
        public static string student_dashboard {
            get {
                return ResourceManager.GetString("student_dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome, Student!.
        /// </summary>
        public static string student_welcome {
            get {
                return ResourceManager.GetString("student_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation do not match..
        /// </summary>
        public static string val_compare {
            get {
                return ResourceManager.GetString("val_compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        public static string val_email {
            get {
                return ResourceManager.GetString("val_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {1} characters..
        /// </summary>
        public static string val_minlength {
            get {
                return ResourceManager.GetString("val_minlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string val_required {
            get {
                return ResourceManager.GetString("val_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to.
        /// </summary>
        public static string website_web {
            get {
                return ResourceManager.GetString("website_web", resourceCulture);
            }
        }
    }
}
